[package]
name = "jaeymo/easy-input"
version = "1.0.1"
description = "Context-based input module, with various input types."
license = "MIT"
authors = ["Jaeymo"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
trove = "sleitnick/trove@1.8.0"
signal = "sleitnick/signal@2.0.3"